image: ubuntu

stages:
  - build

clang-build:
  stage: build
  before_script:
  - apt-get update
  - apt-get install -y build-essential clang
  - apt-get install -y libcairo2-dev
  script:
    - make CC=clang debug

gcc-build:
  stage: build
  before_script:
  - apt-get update
  - apt-get install -y build-essential
  - apt-get install -y libcairo2-dev
  script:
    - make CC=gcc debug
